//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment5Forms.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.CronusServiceSoap")]
    public interface CronusServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadEmployeeAndRelatedTables", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReadEmployeeAndRelatedTables();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadEmployeeAndRelatedTables", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReadEmployeeAndRelatedTablesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadEmployeesAndRelatives", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReadEmployeesAndRelatives();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadEmployeesAndRelatives", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReadEmployeesAndRelativesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadAllSickEmployees2004", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReadAllSickEmployees2004();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadAllSickEmployees2004", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReadAllSickEmployees2004Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadHighestAbsence", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReadHighestAbsence();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadHighestAbsence", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReadHighestAbsenceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadAllKeys", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReadAllKeys();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadAllKeys", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReadAllKeysAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadAllIndexes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReadAllIndexes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadAllIndexes", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReadAllIndexesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadAllConstraints", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReadAllConstraints();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadAllConstraints", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReadAllConstraintsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadAllTables1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReadAllTables1();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadAllTables1", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReadAllTables1Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadAllTables2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReadAllTables2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadAllTables2", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReadAllTables2Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadEmployeeColumns1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReadEmployeeColumns1();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadEmployeeColumns1", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReadEmployeeColumns1Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadEmployeeColumns2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReadEmployeeColumns2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadEmployeeColumns2", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReadEmployeeColumns2Async();
        
        // CODEGEN: Parameter 'ReadEmployeeAndRelatedTablesJavaResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadEmployeeAndRelatedTablesJava", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Assignment5Forms.ServiceReference1.ReadEmployeeAndRelatedTablesJavaResponse ReadEmployeeAndRelatedTablesJava(Assignment5Forms.ServiceReference1.ReadEmployeeAndRelatedTablesJavaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadEmployeeAndRelatedTablesJava", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment5Forms.ServiceReference1.ReadEmployeeAndRelatedTablesJavaResponse> ReadEmployeeAndRelatedTablesJavaAsync(Assignment5Forms.ServiceReference1.ReadEmployeeAndRelatedTablesJavaRequest request);
        
        // CODEGEN: Parameter 'ReadEmployeesAndRelativesJavaResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadEmployeesAndRelativesJava", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Assignment5Forms.ServiceReference1.ReadEmployeesAndRelativesJavaResponse ReadEmployeesAndRelativesJava(Assignment5Forms.ServiceReference1.ReadEmployeesAndRelativesJavaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadEmployeesAndRelativesJava", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment5Forms.ServiceReference1.ReadEmployeesAndRelativesJavaResponse> ReadEmployeesAndRelativesJavaAsync(Assignment5Forms.ServiceReference1.ReadEmployeesAndRelativesJavaRequest request);
        
        // CODEGEN: Parameter 'ReadAllSickEmployees2004JavaResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadAllSickEmployees2004Java", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Assignment5Forms.ServiceReference1.ReadAllSickEmployees2004JavaResponse ReadAllSickEmployees2004Java(Assignment5Forms.ServiceReference1.ReadAllSickEmployees2004JavaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadAllSickEmployees2004Java", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment5Forms.ServiceReference1.ReadAllSickEmployees2004JavaResponse> ReadAllSickEmployees2004JavaAsync(Assignment5Forms.ServiceReference1.ReadAllSickEmployees2004JavaRequest request);
        
        // CODEGEN: Parameter 'ReadHighestAbsenceJavaResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadHighestAbsenceJava", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Assignment5Forms.ServiceReference1.ReadHighestAbsenceJavaResponse ReadHighestAbsenceJava(Assignment5Forms.ServiceReference1.ReadHighestAbsenceJavaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadHighestAbsenceJava", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment5Forms.ServiceReference1.ReadHighestAbsenceJavaResponse> ReadHighestAbsenceJavaAsync(Assignment5Forms.ServiceReference1.ReadHighestAbsenceJavaRequest request);
        
        // CODEGEN: Parameter 'ReadAllKeysJavaResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadAllKeysJava", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Assignment5Forms.ServiceReference1.ReadAllKeysJavaResponse ReadAllKeysJava(Assignment5Forms.ServiceReference1.ReadAllKeysJavaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadAllKeysJava", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment5Forms.ServiceReference1.ReadAllKeysJavaResponse> ReadAllKeysJavaAsync(Assignment5Forms.ServiceReference1.ReadAllKeysJavaRequest request);
        
        // CODEGEN: Parameter 'ReadAllIndexesJavaResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadAllIndexesJava", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Assignment5Forms.ServiceReference1.ReadAllIndexesJavaResponse ReadAllIndexesJava(Assignment5Forms.ServiceReference1.ReadAllIndexesJavaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadAllIndexesJava", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment5Forms.ServiceReference1.ReadAllIndexesJavaResponse> ReadAllIndexesJavaAsync(Assignment5Forms.ServiceReference1.ReadAllIndexesJavaRequest request);
        
        // CODEGEN: Parameter 'ReadAllTableConstraintsJavaResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadAllTableConstraintsJava", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Assignment5Forms.ServiceReference1.ReadAllTableConstraintsJavaResponse ReadAllTableConstraintsJava(Assignment5Forms.ServiceReference1.ReadAllTableConstraintsJavaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadAllTableConstraintsJava", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment5Forms.ServiceReference1.ReadAllTableConstraintsJavaResponse> ReadAllTableConstraintsJavaAsync(Assignment5Forms.ServiceReference1.ReadAllTableConstraintsJavaRequest request);
        
        // CODEGEN: Parameter 'ReadAllTables1JavaResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadAllTables1Java", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Assignment5Forms.ServiceReference1.ReadAllTables1JavaResponse ReadAllTables1Java(Assignment5Forms.ServiceReference1.ReadAllTables1JavaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadAllTables1Java", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment5Forms.ServiceReference1.ReadAllTables1JavaResponse> ReadAllTables1JavaAsync(Assignment5Forms.ServiceReference1.ReadAllTables1JavaRequest request);
        
        // CODEGEN: Parameter 'ReadAllTables2JavaResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadAllTables2Java", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Assignment5Forms.ServiceReference1.ReadAllTables2JavaResponse ReadAllTables2Java(Assignment5Forms.ServiceReference1.ReadAllTables2JavaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadAllTables2Java", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment5Forms.ServiceReference1.ReadAllTables2JavaResponse> ReadAllTables2JavaAsync(Assignment5Forms.ServiceReference1.ReadAllTables2JavaRequest request);
        
        // CODEGEN: Parameter 'ReadEmployeeColumns1JavaResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadEmployeeColumns1Java", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Assignment5Forms.ServiceReference1.ReadEmployeeColumns1JavaResponse ReadEmployeeColumns1Java(Assignment5Forms.ServiceReference1.ReadEmployeeColumns1JavaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadEmployeeColumns1Java", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment5Forms.ServiceReference1.ReadEmployeeColumns1JavaResponse> ReadEmployeeColumns1JavaAsync(Assignment5Forms.ServiceReference1.ReadEmployeeColumns1JavaRequest request);
        
        // CODEGEN: Parameter 'ReadEmployeeColumns2JavaResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadEmployeeColumns2Java", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Assignment5Forms.ServiceReference1.ReadEmployeeColumns2JavaResponse ReadEmployeeColumns2Java(Assignment5Forms.ServiceReference1.ReadEmployeeColumns2JavaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadEmployeeColumns2Java", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment5Forms.ServiceReference1.ReadEmployeeColumns2JavaResponse> ReadEmployeeColumns2JavaAsync(Assignment5Forms.ServiceReference1.ReadEmployeeColumns2JavaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadEmployeeAndRelatedTablesJava", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReadEmployeeAndRelatedTablesJavaRequest {
        
        public ReadEmployeeAndRelatedTablesJavaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadEmployeeAndRelatedTablesJavaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReadEmployeeAndRelatedTablesJavaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] ReadEmployeeAndRelatedTablesJavaResult;
        
        public ReadEmployeeAndRelatedTablesJavaResponse() {
        }
        
        public ReadEmployeeAndRelatedTablesJavaResponse(string[][] ReadEmployeeAndRelatedTablesJavaResult) {
            this.ReadEmployeeAndRelatedTablesJavaResult = ReadEmployeeAndRelatedTablesJavaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadEmployeesAndRelativesJava", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReadEmployeesAndRelativesJavaRequest {
        
        public ReadEmployeesAndRelativesJavaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadEmployeesAndRelativesJavaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReadEmployeesAndRelativesJavaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] ReadEmployeesAndRelativesJavaResult;
        
        public ReadEmployeesAndRelativesJavaResponse() {
        }
        
        public ReadEmployeesAndRelativesJavaResponse(string[][] ReadEmployeesAndRelativesJavaResult) {
            this.ReadEmployeesAndRelativesJavaResult = ReadEmployeesAndRelativesJavaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadAllSickEmployees2004Java", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReadAllSickEmployees2004JavaRequest {
        
        public ReadAllSickEmployees2004JavaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadAllSickEmployees2004JavaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReadAllSickEmployees2004JavaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] ReadAllSickEmployees2004JavaResult;
        
        public ReadAllSickEmployees2004JavaResponse() {
        }
        
        public ReadAllSickEmployees2004JavaResponse(string[][] ReadAllSickEmployees2004JavaResult) {
            this.ReadAllSickEmployees2004JavaResult = ReadAllSickEmployees2004JavaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadHighestAbsenceJava", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReadHighestAbsenceJavaRequest {
        
        public ReadHighestAbsenceJavaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadHighestAbsenceJavaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReadHighestAbsenceJavaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] ReadHighestAbsenceJavaResult;
        
        public ReadHighestAbsenceJavaResponse() {
        }
        
        public ReadHighestAbsenceJavaResponse(string[][] ReadHighestAbsenceJavaResult) {
            this.ReadHighestAbsenceJavaResult = ReadHighestAbsenceJavaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadAllKeysJava", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReadAllKeysJavaRequest {
        
        public ReadAllKeysJavaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadAllKeysJavaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReadAllKeysJavaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] ReadAllKeysJavaResult;
        
        public ReadAllKeysJavaResponse() {
        }
        
        public ReadAllKeysJavaResponse(string[][] ReadAllKeysJavaResult) {
            this.ReadAllKeysJavaResult = ReadAllKeysJavaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadAllIndexesJava", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReadAllIndexesJavaRequest {
        
        public ReadAllIndexesJavaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadAllIndexesJavaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReadAllIndexesJavaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] ReadAllIndexesJavaResult;
        
        public ReadAllIndexesJavaResponse() {
        }
        
        public ReadAllIndexesJavaResponse(string[][] ReadAllIndexesJavaResult) {
            this.ReadAllIndexesJavaResult = ReadAllIndexesJavaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadAllTableConstraintsJava", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReadAllTableConstraintsJavaRequest {
        
        public ReadAllTableConstraintsJavaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadAllTableConstraintsJavaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReadAllTableConstraintsJavaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] ReadAllTableConstraintsJavaResult;
        
        public ReadAllTableConstraintsJavaResponse() {
        }
        
        public ReadAllTableConstraintsJavaResponse(string[][] ReadAllTableConstraintsJavaResult) {
            this.ReadAllTableConstraintsJavaResult = ReadAllTableConstraintsJavaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadAllTables1Java", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReadAllTables1JavaRequest {
        
        public ReadAllTables1JavaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadAllTables1JavaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReadAllTables1JavaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] ReadAllTables1JavaResult;
        
        public ReadAllTables1JavaResponse() {
        }
        
        public ReadAllTables1JavaResponse(string[][] ReadAllTables1JavaResult) {
            this.ReadAllTables1JavaResult = ReadAllTables1JavaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadAllTables2Java", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReadAllTables2JavaRequest {
        
        public ReadAllTables2JavaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadAllTables2JavaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReadAllTables2JavaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] ReadAllTables2JavaResult;
        
        public ReadAllTables2JavaResponse() {
        }
        
        public ReadAllTables2JavaResponse(string[][] ReadAllTables2JavaResult) {
            this.ReadAllTables2JavaResult = ReadAllTables2JavaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadEmployeeColumns1Java", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReadEmployeeColumns1JavaRequest {
        
        public ReadEmployeeColumns1JavaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadEmployeeColumns1JavaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReadEmployeeColumns1JavaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] ReadEmployeeColumns1JavaResult;
        
        public ReadEmployeeColumns1JavaResponse() {
        }
        
        public ReadEmployeeColumns1JavaResponse(string[][] ReadEmployeeColumns1JavaResult) {
            this.ReadEmployeeColumns1JavaResult = ReadEmployeeColumns1JavaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadEmployeeColumns2Java", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReadEmployeeColumns2JavaRequest {
        
        public ReadEmployeeColumns2JavaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadEmployeeColumns2JavaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReadEmployeeColumns2JavaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] ReadEmployeeColumns2JavaResult;
        
        public ReadEmployeeColumns2JavaResponse() {
        }
        
        public ReadEmployeeColumns2JavaResponse(string[][] ReadEmployeeColumns2JavaResult) {
            this.ReadEmployeeColumns2JavaResult = ReadEmployeeColumns2JavaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CronusServiceSoapChannel : Assignment5Forms.ServiceReference1.CronusServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CronusServiceSoapClient : System.ServiceModel.ClientBase<Assignment5Forms.ServiceReference1.CronusServiceSoap>, Assignment5Forms.ServiceReference1.CronusServiceSoap {
        
        public CronusServiceSoapClient() {
        }
        
        public CronusServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CronusServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CronusServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CronusServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ReadEmployeeAndRelatedTables() {
            return base.Channel.ReadEmployeeAndRelatedTables();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReadEmployeeAndRelatedTablesAsync() {
            return base.Channel.ReadEmployeeAndRelatedTablesAsync();
        }
        
        public System.Data.DataSet ReadEmployeesAndRelatives() {
            return base.Channel.ReadEmployeesAndRelatives();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReadEmployeesAndRelativesAsync() {
            return base.Channel.ReadEmployeesAndRelativesAsync();
        }
        
        public System.Data.DataSet ReadAllSickEmployees2004() {
            return base.Channel.ReadAllSickEmployees2004();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReadAllSickEmployees2004Async() {
            return base.Channel.ReadAllSickEmployees2004Async();
        }
        
        public System.Data.DataSet ReadHighestAbsence() {
            return base.Channel.ReadHighestAbsence();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReadHighestAbsenceAsync() {
            return base.Channel.ReadHighestAbsenceAsync();
        }
        
        public System.Data.DataSet ReadAllKeys() {
            return base.Channel.ReadAllKeys();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReadAllKeysAsync() {
            return base.Channel.ReadAllKeysAsync();
        }
        
        public System.Data.DataSet ReadAllIndexes() {
            return base.Channel.ReadAllIndexes();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReadAllIndexesAsync() {
            return base.Channel.ReadAllIndexesAsync();
        }
        
        public System.Data.DataSet ReadAllConstraints() {
            return base.Channel.ReadAllConstraints();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReadAllConstraintsAsync() {
            return base.Channel.ReadAllConstraintsAsync();
        }
        
        public System.Data.DataSet ReadAllTables1() {
            return base.Channel.ReadAllTables1();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReadAllTables1Async() {
            return base.Channel.ReadAllTables1Async();
        }
        
        public System.Data.DataSet ReadAllTables2() {
            return base.Channel.ReadAllTables2();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReadAllTables2Async() {
            return base.Channel.ReadAllTables2Async();
        }
        
        public System.Data.DataSet ReadEmployeeColumns1() {
            return base.Channel.ReadEmployeeColumns1();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReadEmployeeColumns1Async() {
            return base.Channel.ReadEmployeeColumns1Async();
        }
        
        public System.Data.DataSet ReadEmployeeColumns2() {
            return base.Channel.ReadEmployeeColumns2();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReadEmployeeColumns2Async() {
            return base.Channel.ReadEmployeeColumns2Async();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment5Forms.ServiceReference1.ReadEmployeeAndRelatedTablesJavaResponse Assignment5Forms.ServiceReference1.CronusServiceSoap.ReadEmployeeAndRelatedTablesJava(Assignment5Forms.ServiceReference1.ReadEmployeeAndRelatedTablesJavaRequest request) {
            return base.Channel.ReadEmployeeAndRelatedTablesJava(request);
        }
        
        public string[][] ReadEmployeeAndRelatedTablesJava() {
            Assignment5Forms.ServiceReference1.ReadEmployeeAndRelatedTablesJavaRequest inValue = new Assignment5Forms.ServiceReference1.ReadEmployeeAndRelatedTablesJavaRequest();
            Assignment5Forms.ServiceReference1.ReadEmployeeAndRelatedTablesJavaResponse retVal = ((Assignment5Forms.ServiceReference1.CronusServiceSoap)(this)).ReadEmployeeAndRelatedTablesJava(inValue);
            return retVal.ReadEmployeeAndRelatedTablesJavaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assignment5Forms.ServiceReference1.ReadEmployeeAndRelatedTablesJavaResponse> Assignment5Forms.ServiceReference1.CronusServiceSoap.ReadEmployeeAndRelatedTablesJavaAsync(Assignment5Forms.ServiceReference1.ReadEmployeeAndRelatedTablesJavaRequest request) {
            return base.Channel.ReadEmployeeAndRelatedTablesJavaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assignment5Forms.ServiceReference1.ReadEmployeeAndRelatedTablesJavaResponse> ReadEmployeeAndRelatedTablesJavaAsync() {
            Assignment5Forms.ServiceReference1.ReadEmployeeAndRelatedTablesJavaRequest inValue = new Assignment5Forms.ServiceReference1.ReadEmployeeAndRelatedTablesJavaRequest();
            return ((Assignment5Forms.ServiceReference1.CronusServiceSoap)(this)).ReadEmployeeAndRelatedTablesJavaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment5Forms.ServiceReference1.ReadEmployeesAndRelativesJavaResponse Assignment5Forms.ServiceReference1.CronusServiceSoap.ReadEmployeesAndRelativesJava(Assignment5Forms.ServiceReference1.ReadEmployeesAndRelativesJavaRequest request) {
            return base.Channel.ReadEmployeesAndRelativesJava(request);
        }
        
        public string[][] ReadEmployeesAndRelativesJava() {
            Assignment5Forms.ServiceReference1.ReadEmployeesAndRelativesJavaRequest inValue = new Assignment5Forms.ServiceReference1.ReadEmployeesAndRelativesJavaRequest();
            Assignment5Forms.ServiceReference1.ReadEmployeesAndRelativesJavaResponse retVal = ((Assignment5Forms.ServiceReference1.CronusServiceSoap)(this)).ReadEmployeesAndRelativesJava(inValue);
            return retVal.ReadEmployeesAndRelativesJavaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assignment5Forms.ServiceReference1.ReadEmployeesAndRelativesJavaResponse> Assignment5Forms.ServiceReference1.CronusServiceSoap.ReadEmployeesAndRelativesJavaAsync(Assignment5Forms.ServiceReference1.ReadEmployeesAndRelativesJavaRequest request) {
            return base.Channel.ReadEmployeesAndRelativesJavaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assignment5Forms.ServiceReference1.ReadEmployeesAndRelativesJavaResponse> ReadEmployeesAndRelativesJavaAsync() {
            Assignment5Forms.ServiceReference1.ReadEmployeesAndRelativesJavaRequest inValue = new Assignment5Forms.ServiceReference1.ReadEmployeesAndRelativesJavaRequest();
            return ((Assignment5Forms.ServiceReference1.CronusServiceSoap)(this)).ReadEmployeesAndRelativesJavaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment5Forms.ServiceReference1.ReadAllSickEmployees2004JavaResponse Assignment5Forms.ServiceReference1.CronusServiceSoap.ReadAllSickEmployees2004Java(Assignment5Forms.ServiceReference1.ReadAllSickEmployees2004JavaRequest request) {
            return base.Channel.ReadAllSickEmployees2004Java(request);
        }
        
        public string[][] ReadAllSickEmployees2004Java() {
            Assignment5Forms.ServiceReference1.ReadAllSickEmployees2004JavaRequest inValue = new Assignment5Forms.ServiceReference1.ReadAllSickEmployees2004JavaRequest();
            Assignment5Forms.ServiceReference1.ReadAllSickEmployees2004JavaResponse retVal = ((Assignment5Forms.ServiceReference1.CronusServiceSoap)(this)).ReadAllSickEmployees2004Java(inValue);
            return retVal.ReadAllSickEmployees2004JavaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assignment5Forms.ServiceReference1.ReadAllSickEmployees2004JavaResponse> Assignment5Forms.ServiceReference1.CronusServiceSoap.ReadAllSickEmployees2004JavaAsync(Assignment5Forms.ServiceReference1.ReadAllSickEmployees2004JavaRequest request) {
            return base.Channel.ReadAllSickEmployees2004JavaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assignment5Forms.ServiceReference1.ReadAllSickEmployees2004JavaResponse> ReadAllSickEmployees2004JavaAsync() {
            Assignment5Forms.ServiceReference1.ReadAllSickEmployees2004JavaRequest inValue = new Assignment5Forms.ServiceReference1.ReadAllSickEmployees2004JavaRequest();
            return ((Assignment5Forms.ServiceReference1.CronusServiceSoap)(this)).ReadAllSickEmployees2004JavaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment5Forms.ServiceReference1.ReadHighestAbsenceJavaResponse Assignment5Forms.ServiceReference1.CronusServiceSoap.ReadHighestAbsenceJava(Assignment5Forms.ServiceReference1.ReadHighestAbsenceJavaRequest request) {
            return base.Channel.ReadHighestAbsenceJava(request);
        }
        
        public string[][] ReadHighestAbsenceJava() {
            Assignment5Forms.ServiceReference1.ReadHighestAbsenceJavaRequest inValue = new Assignment5Forms.ServiceReference1.ReadHighestAbsenceJavaRequest();
            Assignment5Forms.ServiceReference1.ReadHighestAbsenceJavaResponse retVal = ((Assignment5Forms.ServiceReference1.CronusServiceSoap)(this)).ReadHighestAbsenceJava(inValue);
            return retVal.ReadHighestAbsenceJavaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assignment5Forms.ServiceReference1.ReadHighestAbsenceJavaResponse> Assignment5Forms.ServiceReference1.CronusServiceSoap.ReadHighestAbsenceJavaAsync(Assignment5Forms.ServiceReference1.ReadHighestAbsenceJavaRequest request) {
            return base.Channel.ReadHighestAbsenceJavaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assignment5Forms.ServiceReference1.ReadHighestAbsenceJavaResponse> ReadHighestAbsenceJavaAsync() {
            Assignment5Forms.ServiceReference1.ReadHighestAbsenceJavaRequest inValue = new Assignment5Forms.ServiceReference1.ReadHighestAbsenceJavaRequest();
            return ((Assignment5Forms.ServiceReference1.CronusServiceSoap)(this)).ReadHighestAbsenceJavaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment5Forms.ServiceReference1.ReadAllKeysJavaResponse Assignment5Forms.ServiceReference1.CronusServiceSoap.ReadAllKeysJava(Assignment5Forms.ServiceReference1.ReadAllKeysJavaRequest request) {
            return base.Channel.ReadAllKeysJava(request);
        }
        
        public string[][] ReadAllKeysJava() {
            Assignment5Forms.ServiceReference1.ReadAllKeysJavaRequest inValue = new Assignment5Forms.ServiceReference1.ReadAllKeysJavaRequest();
            Assignment5Forms.ServiceReference1.ReadAllKeysJavaResponse retVal = ((Assignment5Forms.ServiceReference1.CronusServiceSoap)(this)).ReadAllKeysJava(inValue);
            return retVal.ReadAllKeysJavaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assignment5Forms.ServiceReference1.ReadAllKeysJavaResponse> Assignment5Forms.ServiceReference1.CronusServiceSoap.ReadAllKeysJavaAsync(Assignment5Forms.ServiceReference1.ReadAllKeysJavaRequest request) {
            return base.Channel.ReadAllKeysJavaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assignment5Forms.ServiceReference1.ReadAllKeysJavaResponse> ReadAllKeysJavaAsync() {
            Assignment5Forms.ServiceReference1.ReadAllKeysJavaRequest inValue = new Assignment5Forms.ServiceReference1.ReadAllKeysJavaRequest();
            return ((Assignment5Forms.ServiceReference1.CronusServiceSoap)(this)).ReadAllKeysJavaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment5Forms.ServiceReference1.ReadAllIndexesJavaResponse Assignment5Forms.ServiceReference1.CronusServiceSoap.ReadAllIndexesJava(Assignment5Forms.ServiceReference1.ReadAllIndexesJavaRequest request) {
            return base.Channel.ReadAllIndexesJava(request);
        }
        
        public string[][] ReadAllIndexesJava() {
            Assignment5Forms.ServiceReference1.ReadAllIndexesJavaRequest inValue = new Assignment5Forms.ServiceReference1.ReadAllIndexesJavaRequest();
            Assignment5Forms.ServiceReference1.ReadAllIndexesJavaResponse retVal = ((Assignment5Forms.ServiceReference1.CronusServiceSoap)(this)).ReadAllIndexesJava(inValue);
            return retVal.ReadAllIndexesJavaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assignment5Forms.ServiceReference1.ReadAllIndexesJavaResponse> Assignment5Forms.ServiceReference1.CronusServiceSoap.ReadAllIndexesJavaAsync(Assignment5Forms.ServiceReference1.ReadAllIndexesJavaRequest request) {
            return base.Channel.ReadAllIndexesJavaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assignment5Forms.ServiceReference1.ReadAllIndexesJavaResponse> ReadAllIndexesJavaAsync() {
            Assignment5Forms.ServiceReference1.ReadAllIndexesJavaRequest inValue = new Assignment5Forms.ServiceReference1.ReadAllIndexesJavaRequest();
            return ((Assignment5Forms.ServiceReference1.CronusServiceSoap)(this)).ReadAllIndexesJavaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment5Forms.ServiceReference1.ReadAllTableConstraintsJavaResponse Assignment5Forms.ServiceReference1.CronusServiceSoap.ReadAllTableConstraintsJava(Assignment5Forms.ServiceReference1.ReadAllTableConstraintsJavaRequest request) {
            return base.Channel.ReadAllTableConstraintsJava(request);
        }
        
        public string[][] ReadAllTableConstraintsJava() {
            Assignment5Forms.ServiceReference1.ReadAllTableConstraintsJavaRequest inValue = new Assignment5Forms.ServiceReference1.ReadAllTableConstraintsJavaRequest();
            Assignment5Forms.ServiceReference1.ReadAllTableConstraintsJavaResponse retVal = ((Assignment5Forms.ServiceReference1.CronusServiceSoap)(this)).ReadAllTableConstraintsJava(inValue);
            return retVal.ReadAllTableConstraintsJavaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assignment5Forms.ServiceReference1.ReadAllTableConstraintsJavaResponse> Assignment5Forms.ServiceReference1.CronusServiceSoap.ReadAllTableConstraintsJavaAsync(Assignment5Forms.ServiceReference1.ReadAllTableConstraintsJavaRequest request) {
            return base.Channel.ReadAllTableConstraintsJavaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assignment5Forms.ServiceReference1.ReadAllTableConstraintsJavaResponse> ReadAllTableConstraintsJavaAsync() {
            Assignment5Forms.ServiceReference1.ReadAllTableConstraintsJavaRequest inValue = new Assignment5Forms.ServiceReference1.ReadAllTableConstraintsJavaRequest();
            return ((Assignment5Forms.ServiceReference1.CronusServiceSoap)(this)).ReadAllTableConstraintsJavaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment5Forms.ServiceReference1.ReadAllTables1JavaResponse Assignment5Forms.ServiceReference1.CronusServiceSoap.ReadAllTables1Java(Assignment5Forms.ServiceReference1.ReadAllTables1JavaRequest request) {
            return base.Channel.ReadAllTables1Java(request);
        }
        
        public string[][] ReadAllTables1Java() {
            Assignment5Forms.ServiceReference1.ReadAllTables1JavaRequest inValue = new Assignment5Forms.ServiceReference1.ReadAllTables1JavaRequest();
            Assignment5Forms.ServiceReference1.ReadAllTables1JavaResponse retVal = ((Assignment5Forms.ServiceReference1.CronusServiceSoap)(this)).ReadAllTables1Java(inValue);
            return retVal.ReadAllTables1JavaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assignment5Forms.ServiceReference1.ReadAllTables1JavaResponse> Assignment5Forms.ServiceReference1.CronusServiceSoap.ReadAllTables1JavaAsync(Assignment5Forms.ServiceReference1.ReadAllTables1JavaRequest request) {
            return base.Channel.ReadAllTables1JavaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assignment5Forms.ServiceReference1.ReadAllTables1JavaResponse> ReadAllTables1JavaAsync() {
            Assignment5Forms.ServiceReference1.ReadAllTables1JavaRequest inValue = new Assignment5Forms.ServiceReference1.ReadAllTables1JavaRequest();
            return ((Assignment5Forms.ServiceReference1.CronusServiceSoap)(this)).ReadAllTables1JavaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment5Forms.ServiceReference1.ReadAllTables2JavaResponse Assignment5Forms.ServiceReference1.CronusServiceSoap.ReadAllTables2Java(Assignment5Forms.ServiceReference1.ReadAllTables2JavaRequest request) {
            return base.Channel.ReadAllTables2Java(request);
        }
        
        public string[][] ReadAllTables2Java() {
            Assignment5Forms.ServiceReference1.ReadAllTables2JavaRequest inValue = new Assignment5Forms.ServiceReference1.ReadAllTables2JavaRequest();
            Assignment5Forms.ServiceReference1.ReadAllTables2JavaResponse retVal = ((Assignment5Forms.ServiceReference1.CronusServiceSoap)(this)).ReadAllTables2Java(inValue);
            return retVal.ReadAllTables2JavaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assignment5Forms.ServiceReference1.ReadAllTables2JavaResponse> Assignment5Forms.ServiceReference1.CronusServiceSoap.ReadAllTables2JavaAsync(Assignment5Forms.ServiceReference1.ReadAllTables2JavaRequest request) {
            return base.Channel.ReadAllTables2JavaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assignment5Forms.ServiceReference1.ReadAllTables2JavaResponse> ReadAllTables2JavaAsync() {
            Assignment5Forms.ServiceReference1.ReadAllTables2JavaRequest inValue = new Assignment5Forms.ServiceReference1.ReadAllTables2JavaRequest();
            return ((Assignment5Forms.ServiceReference1.CronusServiceSoap)(this)).ReadAllTables2JavaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment5Forms.ServiceReference1.ReadEmployeeColumns1JavaResponse Assignment5Forms.ServiceReference1.CronusServiceSoap.ReadEmployeeColumns1Java(Assignment5Forms.ServiceReference1.ReadEmployeeColumns1JavaRequest request) {
            return base.Channel.ReadEmployeeColumns1Java(request);
        }
        
        public string[][] ReadEmployeeColumns1Java() {
            Assignment5Forms.ServiceReference1.ReadEmployeeColumns1JavaRequest inValue = new Assignment5Forms.ServiceReference1.ReadEmployeeColumns1JavaRequest();
            Assignment5Forms.ServiceReference1.ReadEmployeeColumns1JavaResponse retVal = ((Assignment5Forms.ServiceReference1.CronusServiceSoap)(this)).ReadEmployeeColumns1Java(inValue);
            return retVal.ReadEmployeeColumns1JavaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assignment5Forms.ServiceReference1.ReadEmployeeColumns1JavaResponse> Assignment5Forms.ServiceReference1.CronusServiceSoap.ReadEmployeeColumns1JavaAsync(Assignment5Forms.ServiceReference1.ReadEmployeeColumns1JavaRequest request) {
            return base.Channel.ReadEmployeeColumns1JavaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assignment5Forms.ServiceReference1.ReadEmployeeColumns1JavaResponse> ReadEmployeeColumns1JavaAsync() {
            Assignment5Forms.ServiceReference1.ReadEmployeeColumns1JavaRequest inValue = new Assignment5Forms.ServiceReference1.ReadEmployeeColumns1JavaRequest();
            return ((Assignment5Forms.ServiceReference1.CronusServiceSoap)(this)).ReadEmployeeColumns1JavaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment5Forms.ServiceReference1.ReadEmployeeColumns2JavaResponse Assignment5Forms.ServiceReference1.CronusServiceSoap.ReadEmployeeColumns2Java(Assignment5Forms.ServiceReference1.ReadEmployeeColumns2JavaRequest request) {
            return base.Channel.ReadEmployeeColumns2Java(request);
        }
        
        public string[][] ReadEmployeeColumns2Java() {
            Assignment5Forms.ServiceReference1.ReadEmployeeColumns2JavaRequest inValue = new Assignment5Forms.ServiceReference1.ReadEmployeeColumns2JavaRequest();
            Assignment5Forms.ServiceReference1.ReadEmployeeColumns2JavaResponse retVal = ((Assignment5Forms.ServiceReference1.CronusServiceSoap)(this)).ReadEmployeeColumns2Java(inValue);
            return retVal.ReadEmployeeColumns2JavaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assignment5Forms.ServiceReference1.ReadEmployeeColumns2JavaResponse> Assignment5Forms.ServiceReference1.CronusServiceSoap.ReadEmployeeColumns2JavaAsync(Assignment5Forms.ServiceReference1.ReadEmployeeColumns2JavaRequest request) {
            return base.Channel.ReadEmployeeColumns2JavaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assignment5Forms.ServiceReference1.ReadEmployeeColumns2JavaResponse> ReadEmployeeColumns2JavaAsync() {
            Assignment5Forms.ServiceReference1.ReadEmployeeColumns2JavaRequest inValue = new Assignment5Forms.ServiceReference1.ReadEmployeeColumns2JavaRequest();
            return ((Assignment5Forms.ServiceReference1.CronusServiceSoap)(this)).ReadEmployeeColumns2JavaAsync(inValue);
        }
    }
}
