//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CronusWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRONUS_Sverige_AB_Employee_Portal_Setup
    {
        public byte[] timestamp { get; set; }
        public string Primary_Key { get; set; }
        public int Search_Limit { get; set; }
        public int Temp__Key_Index { get; set; }
        public int Temp__Table_No_ { get; set; }
        public string Temp__Key_String { get; set; }
        public int Temp__Option_Value { get; set; }
        public string Temp__Option_Caption { get; set; }
        public string Temp__SharePoint_Site_Name { get; set; }
        public byte[] Back_End_Public_Key { get; set; }
        public byte[] Back_End_Private_Key { get; set; }
        public byte Write_Debugging_Info_ { get; set; }
        public int Config_Tool_Pane_Caption_ID { get; set; }
        public int Config_TP_WP_Request_Capt_ID { get; set; }
        public int Config_TP_Initial_Req__Capt_ID { get; set; }
        public int Config_TP_Group_Capt_ID { get; set; }
        public int Search_Tool_Pane_Caption_ID { get; set; }
        public int Search_Config_Table_ID { get; set; }
        public int Search_TP_All_Tables_Capt_ID { get; set; }
        public string Config_Tool_Pane_Caption { get; set; }
        public string Config_TP_WP_Request_Caption { get; set; }
        public string Config_TP_Initial_Req__Caption { get; set; }
        public string Config_TP_Group_Caption { get; set; }
        public string Search_Tool_Pane_Caption { get; set; }
        public string Search_Config_Table_Caption { get; set; }
        public string Search_TP_All_Tables_Caption { get; set; }
        public string Debugging_Path { get; set; }
    }
}
